### ISSUE TITLE
Boolean values are serialized as string

### ISSUE THREAD

**Issue by simdevmon** [eclipse/yasson#2]
I tried Yasson `1.0-SNAPSHOT` as described here: http://json-b.net/getting-started.html

Lets say I have a simple class like this:
```
public class MyObject
{
    private String message;
    private boolean flat;

    public MyObject(String message, boolean flat)
    {
        this.message = message;
        this.flat = flat;
    }

    // GETTERS and SETTERS
}
```

Now I want to serialize it to Json using Yasson:

```
System.out.println(
	JsonbBuilder.create().toJson(new MyObject("Hello", true))
);
```

The output is like this:
`{"flat":"true","message":"Hello"}`

I would rather expect this (boolean value should have no quotation marks, since it is not a string). 
`{"flat":true,"message":"Hello"}`

**Comment by bravehorsie** [comment]
Thanks Simon, that was reported and fixed already, I am not sure why changes are lost. I will take a look.

**Comment by m0mus** [comment]
Merged to master.
