### ISSUE TITLE
Dog example can't deserialize/parse given JSON string

### ISSUE THREAD

**Issue by ullenboom** [eclipse/yasson#30]
The line

`dog = jsonb.fromJson("{name:\"Falco\",age:4,bitable:false}", Dog.class);`

is giving an exception. However

`dog = jsonb.fromJson( "{\"age\":4,\"bitable\":false,\"name\":\"Falco\"}", Dog.class );`

works.

**Comment by m0mus** [comment]
Thanks for pointing on it. Fixed 'Getting Started' page should be available on json-b.net now.
