### ISSUE TITLE
module-info lacks dependencies

### ISSUE THREAD

**Issue by marschall** [eclipse/yasson#33]
The [module-info](https://github.com/eclipse/yasson/blob/4b2e6d8c8b4f53d8144fdb188e72f67181d6d780/src/main/java/module-info.java#L14) lists only two dependencies:

* `java.json`
* `java.json.bind`

This is incomplete, several dependencies are missing including the following
* `java.desktop` used for `java.beans.Introspector` by [ClassParser](https://github.com/eclipse/yasson/blob/4b2e6d8c8b4f53d8144fdb188e72f67181d6d780/src/main/java/org/eclipse/yasson/internal/ClassParser.java#L18)
* `java.logging` used for `java.util.logging.Logger` by [ReflectionUtils](https://github.com/eclipse/yasson/blob/4b2e6d8c8b4f53d8144fdb188e72f67181d6d780/src/main/java/org/eclipse/yasson/internal/ReflectionUtils.java) and others
* `java.naming` used for `javax.naming.InitialContext` and `javax.naming.NamingException` by [JsonbComponentInstanceCreatorFactory](https://github.com/eclipse/yasson/blob/4b2e6d8c8b4f53d8144fdb188e72f67181d6d780/src/main/java/org/eclipse/yasson/internal/components/JsonbComponentInstanceCreatorFactory.java)
* CDI used for various classes by [BeanManagerInstanceCreator](https://github.com/eclipse/yasson/blob/4b2e6d8c8b4f53d8144fdb188e72f67181d6d780/src/main/java/org/eclipse/yasson/internal/components/BeanManagerInstanceCreator.java) and [JsonbComponentInstanceCreatorFactory](https://github.com/eclipse/yasson/blob/4b2e6d8c8b4f53d8144fdb188e72f67181d6d780/src/main/java/org/eclipse/yasson/internal/components/JsonbComponentInstanceCreatorFactory.java)

If you're unsure about your dependencies I would recommend using the excellent [jdeps](https://docs.oracle.com/javase/9/tools/jdeps.htm#JSWOR-GUID-A543FEBE-908A-49BF-996C-39499367ADB4) which does a great job of finding your dependencies.

Ideally an automated build can verify the correctness your module declaration.

**Comment by moghaddam** [comment]
Thank you @marschall 

I just added most of them except from CDI which unfortunately is not modularized yet.

**Comment by marschall** [comment]
`java.logging` is still missing.

`java.desktop` is only used for `Introspector.decapitalize` likely a compliant reimplementation could be written and the dependency to `java.desktop` removed? Shall I open a separate issue for this?

**Comment by moghaddam** [comment]
You're right. I misinterpreted the `jdeps` output. `java.logging` is now added. Also regarding the `java.desktop`, I think it would be better to let it be there. It's highly probable that we would need other APIs provided by that module in order to process Java beans.

**Comment by marschall** [comment]
Very well. Should I close this issue, do you want to close it or leave it open?

**Comment by moghaddam** [comment]
I'll close it. Thanks for the contribution.
