### ISSUE TITLE
Deserialisation of nested class fails with compliant: No default constructor found

### ISSUE THREAD

**Issue by readlearncode** [eclipse/yasson#49]
Attempting to deserialize nested class with constructor defined throws **JsonbException: No default constructor found**. 

**Given Json String:**
` {"name":"Inner Class"}`

and 

**Class structure:**
```
public class OuterClass {
    public OuterClass() {}
    public String name = "OuterClass";
    public class InnerClass {
        public InnerClass() {}
        public String name = "Inner Class";
    }
}
```

My reading of the specification section 3.7.2 (Nested Classes) and 3.7.1 (Scope and Field access strategy) is that the above deserialization scenario should work.

Note that adding default constructors does not fix it.

POM: https://github.com/readlearncode/Java-EE-8-Sampler/blob/master/json-b-1-0/pom.xml
CODE: https://github.com/readlearncode/Java-EE-8-Sampler/blob/master/json-b-1-0/src/main/java/com/readlearncode/devWorks/overview/NestedClassExample.java
TEST: https://github.com/readlearncode/Java-EE-8-Sampler/blob/master/json-b-1-0/src/test/java/com/readlearncode/devWorks/overview/NestedClassExampleTest.java

**Comment by bravehorsie** [comment]
In section 3.7 it is defined:

> Any instance passed to a deserialization operation must have a public or protected no-argument
> constructor. Implementations SHOULD throw an error if this condition is not met.

(Throwing an error because of missing no-arg constructor is what happens now using yasson 1.0)

By nature of non-static nested classes, those cannot have default no-arg constructor, because of outer class instance passed inside. 

@m0mus what is your objection on that? Does quoted 3.7 statement apply for non-static nested classes?

**Comment by m0mus** [comment]
@readlearncode Thanks for pointing on this. This is a spec issue. Non-static inner classes support should be removed completely or for deserialization only. I created an issue in JSON-B spec issues tracker here:
https://github.com/javaee/jsonb-spec/issues/68

Closing this issue.
