### ISSUE TITLE
List<> property setter is not called if not annotated.

### ISSUE THREAD

**Issue by redmitry** [eclipse/yasson#54]
Hello,

I have both getter / setter for the List.

```
private List<Publication> publications;
@JsonbProperty("publication")
public List<Publication> getPublications() {
    return publications;
}
@JsonbProperty("publication")
public void setPublications(List<Publication> publications) {
}
```
When where is no annotation for the setter, it is not called on the deserialization.

Is this normal?

Kind regards,

P.S. in JAXB to deserialize it is enough to have only getter which returns an empty collection.

**Comment by moghaddam** [comment]
Hi

You can place `@JsonbProperty` on top of field, getter or setter separately. So if you don't place it on top of the setter, it would not be called on deserialization. If you need it on both serialization and deserialization, it would be better to put it once on top of the property itself.

Regards
Ehsan

**Comment by redmitry** [comment]
I think putting it on the top of private property would have no effect.
On the other hand with the example the problem is (as I understand) that whithout @JsonbProperty on the setter it expects "publication**s**". This is the difference between JAXB / Jackson.

Tank you very much for the clarification.
