### ISSUE TITLE
Inconsistency between spec and Yasson

### ISSUE THREAD

**Issue by readlearncode** [eclipse/yasson#58]
The relates to the implementation of custom Serializers and Deserializers

In the spec (4.7.2 Serializers/Deserializers) the annotations for setting the custom Serializers and Deserializers are specified as `@JsonbSerializer` and `@JsonbDeserializer` however in Yasson they are implemented as `@JsonbTypeSerializer` and `@JsonbTypeDeserializer`.

This would become an issue when swapping out one implementation of JSON-B out for another.

**Comment by m0mus** [comment]
You are right. Spec document has to be updated. @JsonbTypeSerializer and @JsonbTypeDeserializer annotations are actually defined in JSON-B API, so it's not an inconsistency between Yasson and the spec, but inconsistency within a spec.
I created https://github.com/javaee/jsonb-spec/issues/70 in JSON-B spec issues tracker. 
Closing this issue.
