### ISSUE TITLE
Fields marked as JSON properties by PropertyVisibilityStrategy are not (de)serialized

### ISSUE THREAD

**Issue by dirkweil** [eclipse/yasson#60]
Yasson ignores private fields without public setters for desrialization even if fields are marked as JSON properties by means of a PropertyVisibilityStrategy:

Assuming the classes

@JsonbVisibility(JsonAccessType.AllFieldsVisibilityStrategy.class)
public class Country {

  private String name;

  public String getName() {
    return this.name;
  }
// ...
}

public interface JsonAccessType {
  public static class AllFieldsVisibilityStrategy implements PropertyVisibilityStrategy {
    @Override
    public boolean isVisible(Field field) {
      return true;
    }

    @Override
    public boolean isVisible(Method method) {
      return false;
    }
  }
// ...
}

the field Country.name will be ignored for deserialization although it ist marked as JSON property in AllFieldsVisibilityStrategy.

This applies to Yasson at least up to 1.0.1-SNAPSHOT.

A test case is here: https://github.com/GEDOPLAN/issues-jsonb-deserialize-visibilitystrategy.

**Comment by Verdent** [comment]
Hi,
I was able to reproduce this issue at version you have mentioned. I have also verified that this is no longer an issue when I ran your test against the master.
